// Generated by gencpp from file waterplus_map_tools/AddNewWaypoint.msg
// DO NOT EDIT!


#ifndef WATERPLUS_MAP_TOOLS_MESSAGE_ADDNEWWAYPOINT_H
#define WATERPLUS_MAP_TOOLS_MESSAGE_ADDNEWWAYPOINT_H

#include <ros/service_traits.h>


#include <waterplus_map_tools/AddNewWaypointRequest.h>
#include <waterplus_map_tools/AddNewWaypointResponse.h>


namespace waterplus_map_tools
{

struct AddNewWaypoint
{

typedef AddNewWaypointRequest Request;
typedef AddNewWaypointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddNewWaypoint
} // namespace waterplus_map_tools


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::waterplus_map_tools::AddNewWaypoint > {
  static const char* value()
  {
    return "6948a8f076727d2b3b462b6ca2b31b5f";
  }

  static const char* value(const ::waterplus_map_tools::AddNewWaypoint&) { return value(); }
};

template<>
struct DataType< ::waterplus_map_tools::AddNewWaypoint > {
  static const char* value()
  {
    return "waterplus_map_tools/AddNewWaypoint";
  }

  static const char* value(const ::waterplus_map_tools::AddNewWaypoint&) { return value(); }
};


// service_traits::MD5Sum< ::waterplus_map_tools::AddNewWaypointRequest> should match 
// service_traits::MD5Sum< ::waterplus_map_tools::AddNewWaypoint > 
template<>
struct MD5Sum< ::waterplus_map_tools::AddNewWaypointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::waterplus_map_tools::AddNewWaypoint >::value();
  }
  static const char* value(const ::waterplus_map_tools::AddNewWaypointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::waterplus_map_tools::AddNewWaypointRequest> should match 
// service_traits::DataType< ::waterplus_map_tools::AddNewWaypoint > 
template<>
struct DataType< ::waterplus_map_tools::AddNewWaypointRequest>
{
  static const char* value()
  {
    return DataType< ::waterplus_map_tools::AddNewWaypoint >::value();
  }
  static const char* value(const ::waterplus_map_tools::AddNewWaypointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::waterplus_map_tools::AddNewWaypointResponse> should match 
// service_traits::MD5Sum< ::waterplus_map_tools::AddNewWaypoint > 
template<>
struct MD5Sum< ::waterplus_map_tools::AddNewWaypointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::waterplus_map_tools::AddNewWaypoint >::value();
  }
  static const char* value(const ::waterplus_map_tools::AddNewWaypointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::waterplus_map_tools::AddNewWaypointResponse> should match 
// service_traits::DataType< ::waterplus_map_tools::AddNewWaypoint > 
template<>
struct DataType< ::waterplus_map_tools::AddNewWaypointResponse>
{
  static const char* value()
  {
    return DataType< ::waterplus_map_tools::AddNewWaypoint >::value();
  }
  static const char* value(const ::waterplus_map_tools::AddNewWaypointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WATERPLUS_MAP_TOOLS_MESSAGE_ADDNEWWAYPOINT_H
