// Generated by gencpp from file waterplus_map_tools/GetChargerByName.msg
// DO NOT EDIT!


#ifndef WATERPLUS_MAP_TOOLS_MESSAGE_GETCHARGERBYNAME_H
#define WATERPLUS_MAP_TOOLS_MESSAGE_GETCHARGERBYNAME_H

#include <ros/service_traits.h>


#include <waterplus_map_tools/GetChargerByNameRequest.h>
#include <waterplus_map_tools/GetChargerByNameResponse.h>


namespace waterplus_map_tools
{

struct GetChargerByName
{

typedef GetChargerByNameRequest Request;
typedef GetChargerByNameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetChargerByName
} // namespace waterplus_map_tools


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::waterplus_map_tools::GetChargerByName > {
  static const char* value()
  {
    return "5164dc1f215ac8183cbe49b46c7ff40e";
  }

  static const char* value(const ::waterplus_map_tools::GetChargerByName&) { return value(); }
};

template<>
struct DataType< ::waterplus_map_tools::GetChargerByName > {
  static const char* value()
  {
    return "waterplus_map_tools/GetChargerByName";
  }

  static const char* value(const ::waterplus_map_tools::GetChargerByName&) { return value(); }
};


// service_traits::MD5Sum< ::waterplus_map_tools::GetChargerByNameRequest> should match 
// service_traits::MD5Sum< ::waterplus_map_tools::GetChargerByName > 
template<>
struct MD5Sum< ::waterplus_map_tools::GetChargerByNameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::waterplus_map_tools::GetChargerByName >::value();
  }
  static const char* value(const ::waterplus_map_tools::GetChargerByNameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::waterplus_map_tools::GetChargerByNameRequest> should match 
// service_traits::DataType< ::waterplus_map_tools::GetChargerByName > 
template<>
struct DataType< ::waterplus_map_tools::GetChargerByNameRequest>
{
  static const char* value()
  {
    return DataType< ::waterplus_map_tools::GetChargerByName >::value();
  }
  static const char* value(const ::waterplus_map_tools::GetChargerByNameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::waterplus_map_tools::GetChargerByNameResponse> should match 
// service_traits::MD5Sum< ::waterplus_map_tools::GetChargerByName > 
template<>
struct MD5Sum< ::waterplus_map_tools::GetChargerByNameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::waterplus_map_tools::GetChargerByName >::value();
  }
  static const char* value(const ::waterplus_map_tools::GetChargerByNameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::waterplus_map_tools::GetChargerByNameResponse> should match 
// service_traits::DataType< ::waterplus_map_tools::GetChargerByName > 
template<>
struct DataType< ::waterplus_map_tools::GetChargerByNameResponse>
{
  static const char* value()
  {
    return DataType< ::waterplus_map_tools::GetChargerByName >::value();
  }
  static const char* value(const ::waterplus_map_tools::GetChargerByNameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WATERPLUS_MAP_TOOLS_MESSAGE_GETCHARGERBYNAME_H
