// Generated by gencpp from file xfyun_waterplus/IATSwitch.msg
// DO NOT EDIT!


#ifndef XFYUN_WATERPLUS_MESSAGE_IATSWITCH_H
#define XFYUN_WATERPLUS_MESSAGE_IATSWITCH_H

#include <ros/service_traits.h>


#include <xfyun_waterplus/IATSwitchRequest.h>
#include <xfyun_waterplus/IATSwitchResponse.h>


namespace xfyun_waterplus
{

struct IATSwitch
{

typedef IATSwitchRequest Request;
typedef IATSwitchResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct IATSwitch
} // namespace xfyun_waterplus


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xfyun_waterplus::IATSwitch > {
  static const char* value()
  {
    return "d1f8595ffdb7d3156100a6358d5facc1";
  }

  static const char* value(const ::xfyun_waterplus::IATSwitch&) { return value(); }
};

template<>
struct DataType< ::xfyun_waterplus::IATSwitch > {
  static const char* value()
  {
    return "xfyun_waterplus/IATSwitch";
  }

  static const char* value(const ::xfyun_waterplus::IATSwitch&) { return value(); }
};


// service_traits::MD5Sum< ::xfyun_waterplus::IATSwitchRequest> should match 
// service_traits::MD5Sum< ::xfyun_waterplus::IATSwitch > 
template<>
struct MD5Sum< ::xfyun_waterplus::IATSwitchRequest>
{
  static const char* value()
  {
    return MD5Sum< ::xfyun_waterplus::IATSwitch >::value();
  }
  static const char* value(const ::xfyun_waterplus::IATSwitchRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xfyun_waterplus::IATSwitchRequest> should match 
// service_traits::DataType< ::xfyun_waterplus::IATSwitch > 
template<>
struct DataType< ::xfyun_waterplus::IATSwitchRequest>
{
  static const char* value()
  {
    return DataType< ::xfyun_waterplus::IATSwitch >::value();
  }
  static const char* value(const ::xfyun_waterplus::IATSwitchRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xfyun_waterplus::IATSwitchResponse> should match 
// service_traits::MD5Sum< ::xfyun_waterplus::IATSwitch > 
template<>
struct MD5Sum< ::xfyun_waterplus::IATSwitchResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xfyun_waterplus::IATSwitch >::value();
  }
  static const char* value(const ::xfyun_waterplus::IATSwitchResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xfyun_waterplus::IATSwitchResponse> should match 
// service_traits::DataType< ::xfyun_waterplus::IATSwitch > 
template<>
struct DataType< ::xfyun_waterplus::IATSwitchResponse>
{
  static const char* value()
  {
    return DataType< ::xfyun_waterplus::IATSwitch >::value();
  }
  static const char* value(const ::xfyun_waterplus::IATSwitchResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XFYUN_WATERPLUS_MESSAGE_IATSWITCH_H
